algoritmo "ESCOLA"
var
  N1:REAL
  N2:REAL
  media:real
  
inicio
  escreva( "PRIMEIRA NOTA: ")
   leia(N1)
   escreva( " SEGUNDA NOTA: ")
   leia(N2)

   media <- (N1 + N1) /2
   
   escreva("MÉDIA: ", media:4:2)
   
   se (media >= 7) entao
   escreval(" ALUNO APROVADO ")
   senao
   
    se (media >=5) e (media<7) entao
   escreval (" ALUNO em recuperação ")
    senao
   escreval("Aluno reprovado
    fimse
    FIMSE
   
   

   
   
fimalgoritmo
