algoritmo "aula_7"





var


   ano_atual:inteiro
   ano_nasci:inteiro
   idade:inteiro

inicio

      EScreva(" Ano Atual: ")
      leia(ano_atual)
      Escreva(" Ano de Nascimento: ")
      leia(ano_nasci)

      idade <- ano_atual - ano_nasci
       escreval ("IDADE: ",idade )
          se (idade >= 18) entao
         Escreva("APTO A TIRAR CARTEIRA")
           senao
         Escreva("VOCÊ NÃO ESTÁ APTO A TIRAR CARTEIRA")
           fimse

fimalgoritmo


